// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QM.DataAccess.Data;

#nullable disable

namespace QM.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214174419_changeNames")]
    partial class changeNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QM.Models.Actions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("QM.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("QM.Models.Cause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CauseDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Causes");
                });

            modelBuilder.Entity("QM.Models.Mapping.ActionCauseMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionID")
                        .HasColumnType("int");

                    b.Property<int>("CauseID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionID");

                    b.HasIndex("CauseID");

                    b.ToTable("ActionCauseMappings");
                });

            modelBuilder.Entity("QM.Models.Mapping.ActionResponsibleMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsibleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("ResponsibleId");

                    b.ToTable("ActionResponsibleMapping");
                });

            modelBuilder.Entity("QM.Models.Mapping.RequestActionMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionID")
                        .HasColumnType("int");

                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionID");

                    b.HasIndex("RequestID");

                    b.ToTable("RequestActionMappings");
                });

            modelBuilder.Entity("QM.Models.Mapping.RequestCauseMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CauseID")
                        .HasColumnType("int");

                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CauseID");

                    b.HasIndex("RequestID");

                    b.ToTable("RequestCauseMappings");
                });

            modelBuilder.Entity("QM.Models.Mapping.RequestResponsibleMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.Property<int>("ResponsibleID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestID");

                    b.HasIndex("ResponsibleID");

                    b.ToTable("RequestEntityMappings");
                });

            modelBuilder.Entity("QM.Models.Mapping.RequestRiskMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RequestID")
                        .HasColumnType("int");

                    b.Property<int>("RiskID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestID");

                    b.HasIndex("RiskID");

                    b.ToTable("RequestRiskMappings");
                });

            modelBuilder.Entity("QM.Models.Mapping.RiskActionMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionID")
                        .HasColumnType("int");

                    b.Property<int>("RiskID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionID");

                    b.HasIndex("RiskID");

                    b.ToTable("RiskActionMappings");
                });

            modelBuilder.Entity("QM.Models.Mapping.RiskCauseMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CauseID")
                        .HasColumnType("int");

                    b.Property<int>("RiskID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CauseID");

                    b.HasIndex("RiskID");

                    b.ToTable("RiskCauseMappings");
                });

            modelBuilder.Entity("QM.Models.Mapping.RiskStrategicGoalMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RiskId")
                        .HasColumnType("int");

                    b.Property<int>("StrategicGoalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RiskId");

                    b.HasIndex("StrategicGoalId");

                    b.ToTable("RiskGoalMappings");
                });

            modelBuilder.Entity("QM.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpectedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Impact")
                        .HasColumnType("int");

                    b.Property<int>("Likelihood")
                        .HasColumnType("int");

                    b.Property<bool>("Occured")
                        .HasColumnType("bit");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Year")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RiskRequests");
                });

            modelBuilder.Entity("QM.Models.Responsible", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("QM.Models.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int>("Impact")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("likelihood")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("Risks");
                });

            modelBuilder.Entity("QM.Models.StrategicGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GoalDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoalReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StrategicGoals");
                });

            modelBuilder.Entity("QM.Models.WorkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Responsibles");
                });

            modelBuilder.Entity("QM.Models.Mapping.ActionCauseMapping", b =>
                {
                    b.HasOne("QM.Models.Actions", "Action")
                        .WithMany("ActionCauses")
                        .HasForeignKey("ActionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QM.Models.Cause", "Cause")
                        .WithMany("ActionCauses")
                        .HasForeignKey("CauseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Cause");
                });

            modelBuilder.Entity("QM.Models.Mapping.ActionResponsibleMapping", b =>
                {
                    b.HasOne("QM.Models.Actions", "Action")
                        .WithMany("ActionResponsibles")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QM.Models.Responsible", "Responsible")
                        .WithMany("ActionResponsibles")
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("QM.Models.Mapping.RequestActionMapping", b =>
                {
                    b.HasOne("QM.Models.Actions", "Action")
                        .WithMany("RequestActions")
                        .HasForeignKey("ActionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QM.Models.Request", "Request")
                        .WithMany("RequestAction")
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("QM.Models.Mapping.RequestCauseMapping", b =>
                {
                    b.HasOne("QM.Models.Cause", "Cause")
                        .WithMany("RequestCauses")
                        .HasForeignKey("CauseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QM.Models.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cause");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("QM.Models.Mapping.RequestResponsibleMapping", b =>
                {
                    b.HasOne("QM.Models.Request", "Request")
                        .WithMany()
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QM.Models.Responsible", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("QM.Models.Mapping.RequestRiskMapping", b =>
                {
                    b.HasOne("QM.Models.Request", "Request")
                        .WithMany("RequestRisk")
                        .HasForeignKey("RequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QM.Models.Risk", "Risk")
                        .WithMany("RequestRisks")
                        .HasForeignKey("RiskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Risk");
                });

            modelBuilder.Entity("QM.Models.Mapping.RiskActionMapping", b =>
                {
                    b.HasOne("QM.Models.Actions", "Action")
                        .WithMany("RiskActions")
                        .HasForeignKey("ActionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QM.Models.Risk", "Risk")
                        .WithMany("RiskActions")
                        .HasForeignKey("RiskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Risk");
                });

            modelBuilder.Entity("QM.Models.Mapping.RiskCauseMapping", b =>
                {
                    b.HasOne("QM.Models.Cause", "Cause")
                        .WithMany("RiskCauses")
                        .HasForeignKey("CauseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QM.Models.Risk", "Risk")
                        .WithMany("RiskCauses")
                        .HasForeignKey("RiskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cause");

                    b.Navigation("Risk");
                });

            modelBuilder.Entity("QM.Models.Mapping.RiskStrategicGoalMapping", b =>
                {
                    b.HasOne("QM.Models.Risk", "Risk")
                        .WithMany("RiskGoals")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QM.Models.StrategicGoal", "StrategicGoal")
                        .WithMany("RiskGoals")
                        .HasForeignKey("StrategicGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Risk");

                    b.Navigation("StrategicGoal");
                });

            modelBuilder.Entity("QM.Models.Risk", b =>
                {
                    b.HasOne("QM.Models.Category", "Category")
                        .WithMany("Risks")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QM.Models.Actions", b =>
                {
                    b.Navigation("ActionCauses");

                    b.Navigation("ActionResponsibles");

                    b.Navigation("RequestActions");

                    b.Navigation("RiskActions");
                });

            modelBuilder.Entity("QM.Models.Category", b =>
                {
                    b.Navigation("Risks");
                });

            modelBuilder.Entity("QM.Models.Cause", b =>
                {
                    b.Navigation("ActionCauses");

                    b.Navigation("RequestCauses");

                    b.Navigation("RiskCauses");
                });

            modelBuilder.Entity("QM.Models.Request", b =>
                {
                    b.Navigation("RequestAction");

                    b.Navigation("RequestRisk");
                });

            modelBuilder.Entity("QM.Models.Responsible", b =>
                {
                    b.Navigation("ActionResponsibles");
                });

            modelBuilder.Entity("QM.Models.Risk", b =>
                {
                    b.Navigation("RequestRisks");

                    b.Navigation("RiskActions");

                    b.Navigation("RiskCauses");

                    b.Navigation("RiskGoals");
                });

            modelBuilder.Entity("QM.Models.StrategicGoal", b =>
                {
                    b.Navigation("RiskGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
